server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pos_db
    username: pos_user
    password: pos_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Em dev pode usar update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect